### ISSUE TITLE
Add "it doesn't happen on forge"/"it is most likely fabric-only" checkbox in bug reports

### ISSUE THREAD

**Issue by goteusz-maszyk** [Fabricators-of-Create/Create#1329]
### Describe the Suggestion

This repo is only for porting fabric-only features, not adding new & fixing common bugs. Not everyone knows it, so there are many bugs reported here, being in the wrong place.

### Additional Context

Add this to /.github/ISSUE_TEMPLATE/bug_report.yml:
```yaml
- type: checkboxes
  attributes:
    label: This issue is fabric-only
    options:
    - label: The common (forge+fabric) issues should be fixed in upstream forge code, not here.
      required: true
```
